### ISSUE TITLE
Firebase config

### ISSUE THREAD

**Issue by danielfostiak** [VictorShan/tic-tac-toe#30]
Hi Victor,
I’m a student and am really interested in this project you made. I love it. I would really like to talk to you about how you made it including all the undocumented stuff such as the firebase. Would you be able to contact me via email (my email is on my profile page), so we could discuss. That would be greatly appreciated. I know that it’s a bit unorthodox to contact you this way through an issue but it’s the only way I could figure out how, your website didn’t have any method that I could see. 
Thanks, Daniel.

**Comment by VictorShan** [comment]
If you don't mind, I'd like to keep this conversation in this thread in case others have the same question. However, I can also continue this through email if you feel more comfortable.

---

To answer your question, this is definitely not the easiest project to start firebase with. There's a lot of other stuff that is not directly related so it is a huge jump. I would recommend starting off with an easier project. It would probably be easier to start of with this [chat app](https://github.com/VictorShan/cse154-serverless-exploration) one I made while I was a TA.


There are 3 big parts when trying to create this project:
- Authentication/Authorization
- Realtime Updates through Firestore to update game state
- Add player move/game state update sanitization through firebase functions instead of editing database directly to confirm their moves are valid and they aren't changing the state illegally (taking 2 turns, clearing the game board, etc.)

1. I would start with trying to figure out realtime updates through firestore or realtime DB because that is the most impactful part of the project. You would need to subscribe to updates so the game state on the clients update automatically. 
2. Figure out Authentication by first using sign in anonymously. Figure out how the rules for firestore works and how to limit DB read/write by user ID.
3. Configure firebase functions to write to database instead of allowing users to access it directly

LMK what which part you would like more details about

**Comment by danielfostiak** [comment]
Hi Victor,
I would prefer if we could contact via some method such as discord or something like that. This was really insightful, thank you for that breakdown. I have some experience using firebase, also in the newer version than what you used. My main concern is how I can apply these concepts to a different idea I had which also involves similar features to your project such as real-time game rooms. I would like to discuss my idea more privately if that’s okay with you. My discord username is fostiak. If you don’t have/want to use discord, please email me at my email on my profile.

**Comment by VictorShan** [comment]
sent a request on discord
